$axure.loadCurrentPage({
  "url":"电子书后台.html",
  "generationDate":new Date(1474526387535.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c2ce548a57df4e9ab2c21fb66f219ec5",
    "type":"Axure:Page",
    "name":"电子书后台",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3e19e51c717c4d78878e502c06557bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":159},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45f61dd7ef3d46b1a90a3309cb6abcdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":159},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d300311e5c7e491bb045cd06d96152ff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":159},
            "size":{
              "width":347,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3fa7f84c777d4f2db64e562ddac556f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":214},
            "size":{
              "width":53,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"111716dd2d42432fba4f8a247f59d2c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":214},
                "size":{
                  "width":53,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"beb333a096b1485282b80292f40274fc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":209},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f552b3e464d041bca17bd78081fdc833",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":20},
            "size":{
              "width":189,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862da732fc004117a59683fe122a2b7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":20},
                "size":{
                  "width":189,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电子书后台/u6.png"}},
{
          "id":"6a9646d18eb244ada86987c1425ca2c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":70,
              "y":104},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaea674cd5214dfda8a1df7301ec3102",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":70,
                  "y":104},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fb9babc0025474c84ae265f3d395c35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":315},
            "size":{
              "width":27,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666a52110e864e78a8d0efbe58d7d76f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":315},
                "size":{
                  "width":27,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"036a1e5005d54ce396d103a52488e091",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":263},
            "size":{
              "width":137,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"542f89c6c9dd41df81cb985dfdb56efb",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":263},
            "size":{
              "width":140,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"7b1e128deea14fabb6b9bf54ee6905be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC00},
            "location":{
              "x":980,
              "y":159},
            "size":{
              "width":270,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b056a879a8f345639eed8b6b1f12bfc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC00},
                "location":{
                  "x":980,
                  "y":159},
                "size":{
                  "width":270,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电子书后台/u14.png"}},
{
          "id":"5e43bb8271c546c68453b3a29c3d2380",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":570},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98991b2736c14d9c9d176fa26f638833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":570},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电子书后台/u16.png"}},
{
          "id":"7f7a7e46bcd147e3819c28728f88f18b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":115},
            "size":{
              "width":53,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48eab984b0c04f288c1384c27a598965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":115},
                "size":{
                  "width":53,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5707dcbae7f7419d897da1353eea8e17",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":115},
            "size":{
              "width":337,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc28859e15f0419e9611fc5fda76d56f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":692},
            "size":{
              "width":900,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"394f75cdf291435081c2159f2e30f229",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9383ecc4b0cf4e5db0e664774bfc5872",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"7e0f4bc74921412980a1168c2acc6cf6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ff3cf207ffe41f5af3b05d133028b01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"6e9d94c45953413d82e44944795c11d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b2651ceebcb94fe19cf435357f473b3e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"b3a5347d08ec429f9569018a63311b69",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f97d759cd82d42cfb092fe4792bdfc12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"65e438c42a664a5b8aa9b4979c049229",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57b0d85071174a6997bee8fc57303b94",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"6db5dc7632744328bfe0b62b00202435",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"134b606523f145f981d60b611a881dca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"d6040f70951a4edda4b7b264941d74a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"739039c386884c58a8b15840b31756eb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"75c03c75517c4a7382f493da30bd2591",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70d308179bdb4781a6e83474858f5248",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"24b46bfb26d547c69ced5adb4f4855e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba83142a453949708273943b71c1c229",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"1c88e162bf78423b9804003be9d2db17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b6b2622684f640779bb72742f6933860",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"7485616dc6d2404aa5a199bb57c8825e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"32a0c0bbf6af4805b3772031ef0b52a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"05eeef6786c649829813f22b1b564099",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce8a3e5f3a1f46caa6450e7ae31a966e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"b3ba1476cd0b4a0288a29b91420f4a6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67f2ecd742304776aa9af630f7e56769",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"44819b3615c6420c9e0adbf54027723f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3cfc464d7ab48f4935f6e27a1b5d2c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"627847fd3b204512a0073808ecd09c27",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1453f445ecb4b278ae102d014b696e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"ff9457dac30e423c91e1df8f8ca4cd96",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c53dba28f8154bd4bb6e60a557a5a068",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"260aa4369153422c8abbf519c30eff9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ecede90014645829b65171441cc5469",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"075d3dabddce44fb967161f04a6b7332",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f10cbc84732e47c393395f1ba5cde2d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"a08f1d4f53244c1abce134ce9be9ede6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b51c9ee3aae3430991f94ba196072922",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"2e17a8f66e5948feb52f3670b7edf560",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0140a9edb7084496955425934bb55ac3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"2bcd2d8d339740c5ad3d8f5ce37560ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":600,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d73c66aa6d3499d9eb47ca5022e3e1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":600,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"73a403faee1e46dcbaf519bcf15847c2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63940cfcc1f443d3a86ff860117e30e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"5185588c4ccb44a4b4605ff42ee10b53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"462f084f9e394f4793f45a01f4da4d40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u22.png"}},
{
              "id":"7f2e706d17874e0c83fa1eb26271e42b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":700,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b298c11402eb43a197d391b2941de7e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":700,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u58.png"}},
{
              "id":"5a03b2438c564d489262665a6319e6e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"952fdb7526d84fe3b1fc67e3f88d9401",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u38.png"}},
{
              "id":"98d8997a16994f8f936c091a6afa5a32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c8724904f6544a895377f4f690e73bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u38.png"}},
{
              "id":"dd536b3ccb484f309d44e7a96e31f40d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":800,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0474dbb65654200826acf8ae8ed7cf8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":800,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/电子书后台/u74.png"}}]},
{
          "id":"21c3efbfaa994815955213ac0aa48a75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":50},
            "size":{
              "width":123,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db8c472e894b4b5b9c1d552ac3d6b0f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":50},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/电子书后台/u76.png"}},
{
          "id":"5540747c69834e129ed5d63ad70a7ddd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":932},
            "size":{
              "width":333,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9edd0bc5b8c44bcd933e03bb8b6e636c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":932},
                "size":{
                  "width":333,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f910471ac4334236b3e26bf829f73260",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":263},
            "size":{
              "width":53,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48926a904913495a8988a728ff658fde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":263},
                "size":{
                  "width":53,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a26ed8f723646ba84c9bd9ca0af1b29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":420},
            "size":{
              "width":27,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"616473d5d3d04cafbd0fb29dcae40da8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":420},
                "size":{
                  "width":27,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43a77931b6bc47969a5e6f0891402e56",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":300},
            "size":{
              "width":370,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"b307913a58744a2a8b0872d0ad285773",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":420},
            "size":{
              "width":370,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"9db40c7d5ddc4385ba8ff36d32b146fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":214},
            "size":{
              "width":53,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7680b0fd3fe4785b1731a7113e9e3ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":214},
                "size":{
                  "width":53,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9b9fcef1e194b3ab2b26a1675decc23",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":633,
              "y":209},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "3e19e51c717c4d78878e502c06557bec":{
      "scriptId":"u0"},
    "45f61dd7ef3d46b1a90a3309cb6abcdd":{
      "scriptId":"u1"},
    "d300311e5c7e491bb045cd06d96152ff":{
      "scriptId":"u2"},
    "3fa7f84c777d4f2db64e562ddac556f4":{
      "scriptId":"u3"},
    "111716dd2d42432fba4f8a247f59d2c7":{
      "scriptId":"u4"},
    "beb333a096b1485282b80292f40274fc":{
      "scriptId":"u5"},
    "f552b3e464d041bca17bd78081fdc833":{
      "scriptId":"u6"},
    "862da732fc004117a59683fe122a2b7b":{
      "scriptId":"u7"},
    "6a9646d18eb244ada86987c1425ca2c9":{
      "scriptId":"u8"},
    "aaea674cd5214dfda8a1df7301ec3102":{
      "scriptId":"u9"},
    "5fb9babc0025474c84ae265f3d395c35":{
      "scriptId":"u10"},
    "666a52110e864e78a8d0efbe58d7d76f":{
      "scriptId":"u11"},
    "036a1e5005d54ce396d103a52488e091":{
      "scriptId":"u12"},
    "542f89c6c9dd41df81cb985dfdb56efb":{
      "scriptId":"u13"},
    "7b1e128deea14fabb6b9bf54ee6905be":{
      "scriptId":"u14"},
    "b056a879a8f345639eed8b6b1f12bfc9":{
      "scriptId":"u15"},
    "5e43bb8271c546c68453b3a29c3d2380":{
      "scriptId":"u16"},
    "98991b2736c14d9c9d176fa26f638833":{
      "scriptId":"u17"},
    "7f7a7e46bcd147e3819c28728f88f18b":{
      "scriptId":"u18"},
    "48eab984b0c04f288c1384c27a598965":{
      "scriptId":"u19"},
    "5707dcbae7f7419d897da1353eea8e17":{
      "scriptId":"u20"},
    "dc28859e15f0419e9611fc5fda76d56f":{
      "scriptId":"u21"},
    "394f75cdf291435081c2159f2e30f229":{
      "scriptId":"u22"},
    "9383ecc4b0cf4e5db0e664774bfc5872":{
      "scriptId":"u23"},
    "b3a5347d08ec429f9569018a63311b69":{
      "scriptId":"u24"},
    "f97d759cd82d42cfb092fe4792bdfc12":{
      "scriptId":"u25"},
    "d6040f70951a4edda4b7b264941d74a3":{
      "scriptId":"u26"},
    "739039c386884c58a8b15840b31756eb":{
      "scriptId":"u27"},
    "b3ba1476cd0b4a0288a29b91420f4a6d":{
      "scriptId":"u28"},
    "67f2ecd742304776aa9af630f7e56769":{
      "scriptId":"u29"},
    "1c88e162bf78423b9804003be9d2db17":{
      "scriptId":"u30"},
    "b6b2622684f640779bb72742f6933860":{
      "scriptId":"u31"},
    "ff9457dac30e423c91e1df8f8ca4cd96":{
      "scriptId":"u32"},
    "c53dba28f8154bd4bb6e60a557a5a068":{
      "scriptId":"u33"},
    "a08f1d4f53244c1abce134ce9be9ede6":{
      "scriptId":"u34"},
    "b51c9ee3aae3430991f94ba196072922":{
      "scriptId":"u35"},
    "73a403faee1e46dcbaf519bcf15847c2":{
      "scriptId":"u36"},
    "63940cfcc1f443d3a86ff860117e30e3":{
      "scriptId":"u37"},
    "5a03b2438c564d489262665a6319e6e6":{
      "scriptId":"u38"},
    "952fdb7526d84fe3b1fc67e3f88d9401":{
      "scriptId":"u39"},
    "7e0f4bc74921412980a1168c2acc6cf6":{
      "scriptId":"u40"},
    "6ff3cf207ffe41f5af3b05d133028b01":{
      "scriptId":"u41"},
    "65e438c42a664a5b8aa9b4979c049229":{
      "scriptId":"u42"},
    "57b0d85071174a6997bee8fc57303b94":{
      "scriptId":"u43"},
    "75c03c75517c4a7382f493da30bd2591":{
      "scriptId":"u44"},
    "70d308179bdb4781a6e83474858f5248":{
      "scriptId":"u45"},
    "44819b3615c6420c9e0adbf54027723f":{
      "scriptId":"u46"},
    "f3cfc464d7ab48f4935f6e27a1b5d2c5":{
      "scriptId":"u47"},
    "7485616dc6d2404aa5a199bb57c8825e":{
      "scriptId":"u48"},
    "32a0c0bbf6af4805b3772031ef0b52a7":{
      "scriptId":"u49"},
    "260aa4369153422c8abbf519c30eff9e":{
      "scriptId":"u50"},
    "2ecede90014645829b65171441cc5469":{
      "scriptId":"u51"},
    "2e17a8f66e5948feb52f3670b7edf560":{
      "scriptId":"u52"},
    "0140a9edb7084496955425934bb55ac3":{
      "scriptId":"u53"},
    "5185588c4ccb44a4b4605ff42ee10b53":{
      "scriptId":"u54"},
    "462f084f9e394f4793f45a01f4da4d40":{
      "scriptId":"u55"},
    "98d8997a16994f8f936c091a6afa5a32":{
      "scriptId":"u56"},
    "7c8724904f6544a895377f4f690e73bd":{
      "scriptId":"u57"},
    "6e9d94c45953413d82e44944795c11d5":{
      "scriptId":"u58"},
    "b2651ceebcb94fe19cf435357f473b3e":{
      "scriptId":"u59"},
    "6db5dc7632744328bfe0b62b00202435":{
      "scriptId":"u60"},
    "134b606523f145f981d60b611a881dca":{
      "scriptId":"u61"},
    "24b46bfb26d547c69ced5adb4f4855e5":{
      "scriptId":"u62"},
    "ba83142a453949708273943b71c1c229":{
      "scriptId":"u63"},
    "627847fd3b204512a0073808ecd09c27":{
      "scriptId":"u64"},
    "b1453f445ecb4b278ae102d014b696e0":{
      "scriptId":"u65"},
    "05eeef6786c649829813f22b1b564099":{
      "scriptId":"u66"},
    "ce8a3e5f3a1f46caa6450e7ae31a966e":{
      "scriptId":"u67"},
    "075d3dabddce44fb967161f04a6b7332":{
      "scriptId":"u68"},
    "f10cbc84732e47c393395f1ba5cde2d6":{
      "scriptId":"u69"},
    "2bcd2d8d339740c5ad3d8f5ce37560ee":{
      "scriptId":"u70"},
    "9d73c66aa6d3499d9eb47ca5022e3e1b":{
      "scriptId":"u71"},
    "7f2e706d17874e0c83fa1eb26271e42b":{
      "scriptId":"u72"},
    "b298c11402eb43a197d391b2941de7e1":{
      "scriptId":"u73"},
    "dd536b3ccb484f309d44e7a96e31f40d":{
      "scriptId":"u74"},
    "d0474dbb65654200826acf8ae8ed7cf8":{
      "scriptId":"u75"},
    "21c3efbfaa994815955213ac0aa48a75":{
      "scriptId":"u76"},
    "db8c472e894b4b5b9c1d552ac3d6b0f7":{
      "scriptId":"u77"},
    "5540747c69834e129ed5d63ad70a7ddd":{
      "scriptId":"u78"},
    "9edd0bc5b8c44bcd933e03bb8b6e636c":{
      "scriptId":"u79"},
    "f910471ac4334236b3e26bf829f73260":{
      "scriptId":"u80"},
    "48926a904913495a8988a728ff658fde":{
      "scriptId":"u81"},
    "0a26ed8f723646ba84c9bd9ca0af1b29":{
      "scriptId":"u82"},
    "616473d5d3d04cafbd0fb29dcae40da8":{
      "scriptId":"u83"},
    "43a77931b6bc47969a5e6f0891402e56":{
      "scriptId":"u84"},
    "b307913a58744a2a8b0872d0ad285773":{
      "scriptId":"u85"},
    "9db40c7d5ddc4385ba8ff36d32b146fe":{
      "scriptId":"u86"},
    "c7680b0fd3fe4785b1731a7113e9e3ae":{
      "scriptId":"u87"},
    "d9b9fcef1e194b3ab2b26a1675decc23":{
      "scriptId":"u88"}}});