$axure.loadCurrentPage({
  "url":"小会详情页-pc.html",
  "generationDate":new Date(1474526393515.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d24c3b51b92449d5a13ec8081c8c999d",
    "type":"Axure:Page",
    "name":"小会详情页-PC",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"85780821cdb345b4906eb66928929669",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":710},
            "size":{
              "width":840,
              "height":520},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f2a5f3e3744df58ca1edfbd9845af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":710},
                "size":{
                  "width":840,
                  "height":520},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小会详情页-pc/u0.png"}},
{
          "id":"f687325ca935422fb038e5a1f7d1ebfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":340},
            "size":{
              "width":1170,
              "height":300},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6435eb1237c44854a6e9f60c73c33967",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":340},
                "size":{
                  "width":1170,
                  "height":300},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大会_详情页-pc/u2.png"}},
{
          "id":"f74e33f459aa4312b34367360396c41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1240,
              "y":1150},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d0a6cfcfe5042429f204182a6835a25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1240,
                  "y":1150},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"2661c0e620e04b5faf93dc82f9609ace",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":1240,
              "y":1060},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"577d43819ca143508e58132a0354a190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":1240,
                  "y":1060},
                "size":{
                  "width":100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"e99d5b1292284589883daa07d5290003",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":2000},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c34da1f1cfec4742ad51a5a752bf3d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":2000},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/tag列表页/u429.png"}},
{
          "id":"ba7545f2302a4782aa7ef8705a36f695",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":2000},
            "size":{
              "width":1170,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f497fedad964bfaae9fdbaf765b811c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":2000},
                "size":{
                  "width":1170,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源页/u74.png"}},
{
          "id":"e5da837844fd46bcaf1d6751ce92dab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":577,
              "y":2062},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b44ef70ef3d453e97154d6fe1a95897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":577,
                  "y":2062},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7baf52512964a869239e28a75e6a732",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":936,
              "y":2062},
            "size":{
              "width":161,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee52141d889448881632b9a984506ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":936,
                  "y":2062},
                "size":{
                  "width":161,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0eaebac6f2084d349c4f43314c444332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":35,
              "y":2062},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aecae7f4b03d49159136ea80414b2df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":35,
                  "y":2062},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"613374343f994d28bfaa1ce95d8b270e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":312,
              "y":2062},
            "size":{
              "width":132,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad67f9e3d61b41b28b4f0244004835e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":312,
                  "y":2062},
                "size":{
                  "width":132,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8112aaf712e4870920964446a959d91",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"0ac814244e1545bcb944cb3a5dab04c0"},
{
          "id":"6e005e703de5411db8e271e593e2d723",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":21,
              "y":110},
            "size":{
              "width":960,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2097e3ed9f394e138ffaf3fabbadc5cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":21,
                  "y":110},
                "size":{
                  "width":960,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u26.png"}},
{
          "id":"611332816f794d0396ea2cb43aa260e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":990,
              "y":110},
            "size":{
              "width":200,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba1d8f7b8374b99aa801b857c2eca71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":110},
                "size":{
                  "width":200,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u28.png"}},
{
          "id":"b2df9d9cc68540c8898c4630bccf4e4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":20,
              "y":220},
            "size":{
              "width":1170,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea2c2030e59b456f80fc54d5d791cb17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":220},
                "size":{
                  "width":1170,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u30.png"}},
{
          "id":"9bfdc7db0b79408ca007214ff895c98c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":423,
              "y":412},
            "size":{
              "width":315,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b581f0be7b45bbbf9e16f63370cd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":423,
                  "y":412},
                "size":{
                  "width":315,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1e85d8fdfb64ea89a613522f9e768df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":450,
              "y":484},
            "size":{
              "width":63,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f78458d5d7924971be9bd8956c11e336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":450,
                  "y":484},
                "size":{
                  "width":63,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d766c6443a343bc8c47c7693693298e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":30,
              "y":748},
            "size":{
              "width":390,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c334b0fcc3544268943dc49d29916c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":30,
                  "y":748},
                "size":{
                  "width":390,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98fc0a19532d45e9974794b80ccf93d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":713},
            "size":{
              "width":300,
              "height":550},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02751a478dfd468bac2f26fefdf9c20d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":713},
                "size":{
                  "width":300,
                  "height":550},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大会_详情页-pc/u88.png"}},
{
          "id":"658601c0f44c4358aeb97eca05263fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":902,
              "y":731},
            "size":{
              "width":108,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6967dd90af44b9f9946ea1af6240df0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":902,
                  "y":731},
                "size":{
                  "width":108,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d49508410094514baec0b3333dc6e0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":783},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e01e1589924485eb626f6b88266e52a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":783},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5f37819ee6c44dca2c2cc8304962214",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":809},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c0fb6d33864ed7b9d19e64cc411c4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":809},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07481bff6b15480587618af1f8adb68d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":846},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec7a8673ab5465fb7a548732bbec0cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":846},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ade596112a482ab67acdd61f7d22d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":872},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c43dfc37b64127b03c0d772a3b8bb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":872},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9308baba589548d494c699ceba9f2591",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":909},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7fbbfad30f457ea2f192a469701443",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":909},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6312cfcd165844fc8b4bd771b3210f3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":935},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dfc9af714854f2086224ffbe5d9e1d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":935},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fedca66ab4a941b28544dbeb4aef4cb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":972},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e03efe9c267e414fac3734b0f6f7ca8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":972},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3c15d99701a47959aada3bcd1f65ad6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":998},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12585385c8a94263be0cea2a3a766541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":998},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05ed06dbdb2b41719e9c8b970c072590",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":1035},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca2364c283140399cbbec7a423f906e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":1035},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e2e82f7b9f54732952b688b5f4324e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":1061},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8bde67e44a1439daf19c51091c83115",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":1061},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f74d9bda4a94172a6c59f61ba31dc9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":1098},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b623e6f4cc624e158db780719598fdaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":1098},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"267cf77fde5a4b178b7f16fb05d28c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":1124},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38954c3a4fe94c3bad46e8d6c215a73f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":1124},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88377503e1d64eedaf395b282a2221ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":896,
              "y":1161},
            "size":{
              "width":287,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb8e175256349e2b97b5f0aba908d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":896,
                  "y":1161},
                "size":{
                  "width":287,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"150fff58afce4c0f94433b67b0379a8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":1187},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"663cc41d36634cee8a3b196be2fdcb11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":1187},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f206ab60f8942978e1f98c81e9afdd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":513},
            "size":{
              "width":40,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f8b1e8e22b8472a85613fa7c65f4f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":513},
                "size":{
                  "width":40,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源页/u332.png"}},
{
          "id":"29979bfd788d4f50a66c867376d1444c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":513},
            "size":{
              "width":40,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11c96e32a2849ab9e5d0721e9c6b4c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":970,
                  "y":513},
                "size":{
                  "width":40,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/资源页/u332.png"}},
{
          "id":"c97749c8a6ec40d7bc8a816ea7fc0d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":695,
              "y":657},
            "size":{
              "width":140,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2ed26faec742e28363e825dbe0bc83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":695,
                  "y":657},
                "size":{
                  "width":140,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "annotation":{
            "描述":"批量下载专辑的所有资源，按专辑创建者所定积分扣除"},
          "images":{
            "normal~":"images/专辑详情页/u443.png"}},
{
          "id":"c0af89ecfe2f40e78e53a8174cc28fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":625,
              "y":789},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f6e7167af14b4081ab91871a9d97b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":625,
                  "y":789},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e815da312b094cb5a27861b4eb8d861f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":98,
              "y":790},
            "size":{
              "width":161,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306caf421602460989aae60193816567",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":790},
                "size":{
                  "width":161,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43614e698af54e9e8037c72274d75cd2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":769,
              "y":767},
            "size":{
              "width":10,
              "height":16},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/大会_详情页-pc/u66_end.png",
            "line~":"images/大会_详情页-pc/u66_line.png"}},
{
          "id":"1d6baa2211c94ad7a580f8c4039a5cd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":779},
            "size":{
              "width":30,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大会_详情页-pc/u67_line.png"}},
{
          "id":"01ab06e615a34ed8b7767591e4f1a516",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":780},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01101acba23448c6b9a8d0c8159a1062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":780},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大会_详情页-pc/u68.png"}},
{
          "id":"b09e39e03675461bad7edbf20926a72e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":830},
            "size":{
              "width":785,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大会_详情页-pc/u70_line.png"}},
{
          "id":"3a24100e796f42219d7466be40d99601",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":790},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f9978af3fa48f18626900ab2cea860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":790},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b23206a16c27480f8896132fd572314c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":30,
              "y":869},
            "size":{
              "width":390,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0663b1cc534841adf5e1a13663cf81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":30,
                  "y":869},
                "size":{
                  "width":390,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80dfbda280b2464d96839f27282787d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":625,
              "y":910},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6803a6b3684876827dab10ffed1986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":625,
                  "y":910},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"366507f87ae9464094c573b046e4ad2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":98,
              "y":911},
            "size":{
              "width":161,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8072d36c39564d929de33f3a95ca39cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":911},
                "size":{
                  "width":161,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7858a949e5344f658059b3ed29027612",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":769,
              "y":888},
            "size":{
              "width":10,
              "height":16},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/大会_详情页-pc/u66_end.png",
            "line~":"images/大会_详情页-pc/u66_line.png"}},
{
          "id":"4593a81c89e348d2af57d7427b709dee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":900},
            "size":{
              "width":30,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大会_详情页-pc/u67_line.png"}},
{
          "id":"aaa485dd561b4ba183403e096e6a046e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":901},
            "size":{
              "width":36,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0050621a81c8419e91d0de36597ac8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":35,
                  "y":901},
                "size":{
                  "width":36,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/大会_详情页-pc/u68.png"}},
{
          "id":"2d7ec2cf03d74f489c3a5f7a74af648a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":951},
            "size":{
              "width":785,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/大会_详情页-pc/u70_line.png"}},
{
          "id":"e4e42bd0011748b69452c9fa81051b2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":911},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"017b1a95f7e94d26ae80a65421e1826a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":911},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c900d41816a45cdbb812e73818435b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":513},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3435463d09d4be6a341747a89c3358d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":513},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "0ac814244e1545bcb944cb3a5dab04c0":{
      "packageId":"0ac814244e1545bcb944cb3a5dab04c0",
      "type":"Axure:Master",
      "name":"nav",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3d8fa57c70e94e289070d6fed3eae54f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":47},
              "size":{
                "width":1200,
                "height":42},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e509b62fa43b489dad803999971cd60d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":47},
                  "size":{
                    "width":1200,
                    "height":42},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u337.png"}},
{
            "id":"0a7c20091c4b49efa2ea4087d9614082",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fill":{
                "fillType":"solid",
                "color":0xFF48525E},
              "location":{
                "x":0,
                "y":2},
              "size":{
                "width":1200,
                "height":42},
              "linePattern":"none"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a40526e021c48c784528d8a4aedb8bc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF48525E},
                  "location":{
                    "x":0,
                    "y":2},
                  "size":{
                    "width":1200,
                    "height":42},
                  "linePattern":"none"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u339.png"}},
{
            "id":"6d517a2e6a534d3aa2bef4515bcad90d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":44,
                "y":3},
              "size":{
                "width":40,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa5aebdcd28b40139b343f52231a21d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":44,
                    "y":3},
                  "size":{
                    "width":40,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u341.png"}},
{
            "id":"2dd7e7a449d346ab8c02b65a3f4f81a1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "location":{
                "x":762,
                "y":3},
              "size":{
                "width":248,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"de6ade4243bb43a091b45092f9fcd79e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "location":{
                    "x":762,
                    "y":3},
                  "size":{
                    "width":248,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u343.png"}},
{
            "id":"de132481da1c415a9dcd0180195e128d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"20px",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":95,
                "y":8},
              "size":{
                "width":105,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e08860264a9c45fc862f9918bd9b9873",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"20px",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":95,
                    "y":8},
                  "size":{
                    "width":105,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e1a7c52edaae47a9b813bfe00cdd1c48",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":87},
              "size":{
                "width":1170,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE3E3E3}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u347_line.png"}},
{
            "id":"9ceca4f489bc4a2c9a4c871a1cc1b960",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":45,
                "y":87},
              "size":{
                "width":45,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFC04617}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页/u348_line.png"}},
{
            "id":"c1072e05af0949a5bb32789b3130eae7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":51,
                "y":60},
              "size":{
                "width":33,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ae7ec1da1ef2443291d84bb7e6295003",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":51,
                    "y":60},
                  "size":{
                    "width":33,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"eb803ed859bc4ceaa7a0f7684348b27d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":408,
                "y":60},
              "size":{
                "width":65,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44cae1ea08d04b28afc3a464ac927c89",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":408,
                    "y":60},
                  "size":{
                    "width":65,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03043b9d88fa45668a60fed7db8d3ccf",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":303,
                "y":60},
              "size":{
                "width":49,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d87dc5f9f391406e966c1b0463ca74a3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":303,
                    "y":60},
                  "size":{
                    "width":49,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setPanelState",
                        "description":"Set Panel to State",
                        "panelsToStates":[]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c734be2b6a19434599f9e81feebec9f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":140,
                "y":60},
              "size":{
                "width":33,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"398edd9d7efe4b779a0fcd1ebf683e9d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":140,
                    "y":60},
                  "size":{
                    "width":33,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"aabb686e23e645bcb158285384850d2a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":230,
                "y":60},
              "size":{
                "width":33,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68e958f52f22414aa70e770963cfa62f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":230,
                    "y":60},
                  "size":{
                    "width":33,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"23bfbc6f65164100b1589fef8bc060b5",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":762,
                "y":58},
              "size":{
                "width":248,
                "height":25}},
            "adaptiveStyles":{
}}]}}},
  "objectPaths":{
    "85780821cdb345b4906eb66928929669":{
      "scriptId":"u0"},
    "65f2a5f3e3744df58ca1edfbd9845af6":{
      "scriptId":"u1"},
    "f687325ca935422fb038e5a1f7d1ebfd":{
      "scriptId":"u2"},
    "6435eb1237c44854a6e9f60c73c33967":{
      "scriptId":"u3"},
    "f74e33f459aa4312b34367360396c41d":{
      "scriptId":"u4"},
    "9d0a6cfcfe5042429f204182a6835a25":{
      "scriptId":"u5"},
    "2661c0e620e04b5faf93dc82f9609ace":{
      "scriptId":"u6"},
    "577d43819ca143508e58132a0354a190":{
      "scriptId":"u7"},
    "e99d5b1292284589883daa07d5290003":{
      "scriptId":"u8"},
    "c34da1f1cfec4742ad51a5a752bf3d26":{
      "scriptId":"u9"},
    "ba7545f2302a4782aa7ef8705a36f695":{
      "scriptId":"u10"},
    "8f497fedad964bfaae9fdbaf765b811c":{
      "scriptId":"u11"},
    "e5da837844fd46bcaf1d6751ce92dab2":{
      "scriptId":"u12"},
    "9b44ef70ef3d453e97154d6fe1a95897":{
      "scriptId":"u13"},
    "b7baf52512964a869239e28a75e6a732":{
      "scriptId":"u14"},
    "3ee52141d889448881632b9a984506ac":{
      "scriptId":"u15"},
    "0eaebac6f2084d349c4f43314c444332":{
      "scriptId":"u16"},
    "aecae7f4b03d49159136ea80414b2df1":{
      "scriptId":"u17"},
    "613374343f994d28bfaa1ce95d8b270e":{
      "scriptId":"u18"},
    "ad67f9e3d61b41b28b4f0244004835e4":{
      "scriptId":"u19"},
    "c8112aaf712e4870920964446a959d91":{
      "scriptId":"u20",
      "3d8fa57c70e94e289070d6fed3eae54f":{
        "scriptId":"u21"},
      "e509b62fa43b489dad803999971cd60d":{
        "scriptId":"u22"},
      "0a7c20091c4b49efa2ea4087d9614082":{
        "scriptId":"u23"},
      "5a40526e021c48c784528d8a4aedb8bc":{
        "scriptId":"u24"},
      "6d517a2e6a534d3aa2bef4515bcad90d":{
        "scriptId":"u25"},
      "aa5aebdcd28b40139b343f52231a21d9":{
        "scriptId":"u26"},
      "2dd7e7a449d346ab8c02b65a3f4f81a1":{
        "scriptId":"u27"},
      "de6ade4243bb43a091b45092f9fcd79e":{
        "scriptId":"u28"},
      "de132481da1c415a9dcd0180195e128d":{
        "scriptId":"u29"},
      "e08860264a9c45fc862f9918bd9b9873":{
        "scriptId":"u30"},
      "e1a7c52edaae47a9b813bfe00cdd1c48":{
        "scriptId":"u31"},
      "9ceca4f489bc4a2c9a4c871a1cc1b960":{
        "scriptId":"u32"},
      "c1072e05af0949a5bb32789b3130eae7":{
        "scriptId":"u33"},
      "ae7ec1da1ef2443291d84bb7e6295003":{
        "scriptId":"u34"},
      "eb803ed859bc4ceaa7a0f7684348b27d":{
        "scriptId":"u35"},
      "44cae1ea08d04b28afc3a464ac927c89":{
        "scriptId":"u36"},
      "03043b9d88fa45668a60fed7db8d3ccf":{
        "scriptId":"u37"},
      "d87dc5f9f391406e966c1b0463ca74a3":{
        "scriptId":"u38"},
      "c734be2b6a19434599f9e81feebec9f8":{
        "scriptId":"u39"},
      "398edd9d7efe4b779a0fcd1ebf683e9d":{
        "scriptId":"u40"},
      "aabb686e23e645bcb158285384850d2a":{
        "scriptId":"u41"},
      "68e958f52f22414aa70e770963cfa62f":{
        "scriptId":"u42"},
      "23bfbc6f65164100b1589fef8bc060b5":{
        "scriptId":"u43"}},
    "6e005e703de5411db8e271e593e2d723":{
      "scriptId":"u44"},
    "2097e3ed9f394e138ffaf3fabbadc5cc":{
      "scriptId":"u45"},
    "611332816f794d0396ea2cb43aa260e5":{
      "scriptId":"u46"},
    "1ba1d8f7b8374b99aa801b857c2eca71":{
      "scriptId":"u47"},
    "b2df9d9cc68540c8898c4630bccf4e4a":{
      "scriptId":"u48"},
    "ea2c2030e59b456f80fc54d5d791cb17":{
      "scriptId":"u49"},
    "9bfdc7db0b79408ca007214ff895c98c":{
      "scriptId":"u50"},
    "99b581f0be7b45bbbf9e16f63370cd5e":{
      "scriptId":"u51"},
    "e1e85d8fdfb64ea89a613522f9e768df":{
      "scriptId":"u52"},
    "f78458d5d7924971be9bd8956c11e336":{
      "scriptId":"u53"},
    "1d766c6443a343bc8c47c7693693298e":{
      "scriptId":"u54"},
    "c334b0fcc3544268943dc49d29916c60":{
      "scriptId":"u55"},
    "98fc0a19532d45e9974794b80ccf93d5":{
      "scriptId":"u56"},
    "02751a478dfd468bac2f26fefdf9c20d":{
      "scriptId":"u57"},
    "658601c0f44c4358aeb97eca05263fab":{
      "scriptId":"u58"},
    "d6967dd90af44b9f9946ea1af6240df0":{
      "scriptId":"u59"},
    "5d49508410094514baec0b3333dc6e0b":{
      "scriptId":"u60"},
    "7e01e1589924485eb626f6b88266e52a":{
      "scriptId":"u61"},
    "f5f37819ee6c44dca2c2cc8304962214":{
      "scriptId":"u62"},
    "27c0fb6d33864ed7b9d19e64cc411c4c":{
      "scriptId":"u63"},
    "07481bff6b15480587618af1f8adb68d":{
      "scriptId":"u64"},
    "2ec7a8673ab5465fb7a548732bbec0cd":{
      "scriptId":"u65"},
    "40ade596112a482ab67acdd61f7d22d6":{
      "scriptId":"u66"},
    "61c43dfc37b64127b03c0d772a3b8bb2":{
      "scriptId":"u67"},
    "9308baba589548d494c699ceba9f2591":{
      "scriptId":"u68"},
    "8d7fbbfad30f457ea2f192a469701443":{
      "scriptId":"u69"},
    "6312cfcd165844fc8b4bd771b3210f3a":{
      "scriptId":"u70"},
    "6dfc9af714854f2086224ffbe5d9e1d7":{
      "scriptId":"u71"},
    "fedca66ab4a941b28544dbeb4aef4cb5":{
      "scriptId":"u72"},
    "e03efe9c267e414fac3734b0f6f7ca8d":{
      "scriptId":"u73"},
    "a3c15d99701a47959aada3bcd1f65ad6":{
      "scriptId":"u74"},
    "12585385c8a94263be0cea2a3a766541":{
      "scriptId":"u75"},
    "05ed06dbdb2b41719e9c8b970c072590":{
      "scriptId":"u76"},
    "3ca2364c283140399cbbec7a423f906e":{
      "scriptId":"u77"},
    "1e2e82f7b9f54732952b688b5f4324e5":{
      "scriptId":"u78"},
    "c8bde67e44a1439daf19c51091c83115":{
      "scriptId":"u79"},
    "2f74d9bda4a94172a6c59f61ba31dc9f":{
      "scriptId":"u80"},
    "b623e6f4cc624e158db780719598fdaf":{
      "scriptId":"u81"},
    "267cf77fde5a4b178b7f16fb05d28c32":{
      "scriptId":"u82"},
    "38954c3a4fe94c3bad46e8d6c215a73f":{
      "scriptId":"u83"},
    "88377503e1d64eedaf395b282a2221ed":{
      "scriptId":"u84"},
    "4fb8e175256349e2b97b5f0aba908d35":{
      "scriptId":"u85"},
    "150fff58afce4c0f94433b67b0379a8d":{
      "scriptId":"u86"},
    "663cc41d36634cee8a3b196be2fdcb11":{
      "scriptId":"u87"},
    "5f206ab60f8942978e1f98c81e9afdd5":{
      "scriptId":"u88"},
    "5f8b1e8e22b8472a85613fa7c65f4f60":{
      "scriptId":"u89"},
    "29979bfd788d4f50a66c867376d1444c":{
      "scriptId":"u90"},
    "c11c96e32a2849ab9e5d0721e9c6b4c4":{
      "scriptId":"u91"},
    "c97749c8a6ec40d7bc8a816ea7fc0d45":{
      "scriptId":"u92"},
    "6b2ed26faec742e28363e825dbe0bc83":{
      "scriptId":"u93"},
    "c0af89ecfe2f40e78e53a8174cc28fac":{
      "scriptId":"u94"},
    "a3f6e7167af14b4081ab91871a9d97b0":{
      "scriptId":"u95"},
    "e815da312b094cb5a27861b4eb8d861f":{
      "scriptId":"u96"},
    "306caf421602460989aae60193816567":{
      "scriptId":"u97"},
    "43614e698af54e9e8037c72274d75cd2":{
      "scriptId":"u98"},
    "1d6baa2211c94ad7a580f8c4039a5cd8":{
      "scriptId":"u99"},
    "01ab06e615a34ed8b7767591e4f1a516":{
      "scriptId":"u100"},
    "01101acba23448c6b9a8d0c8159a1062":{
      "scriptId":"u101"},
    "b09e39e03675461bad7edbf20926a72e":{
      "scriptId":"u102"},
    "3a24100e796f42219d7466be40d99601":{
      "scriptId":"u103"},
    "10f9978af3fa48f18626900ab2cea860":{
      "scriptId":"u104"},
    "b23206a16c27480f8896132fd572314c":{
      "scriptId":"u105"},
    "0b0663b1cc534841adf5e1a13663cf81":{
      "scriptId":"u106"},
    "80dfbda280b2464d96839f27282787d6":{
      "scriptId":"u107"},
    "fe6803a6b3684876827dab10ffed1986":{
      "scriptId":"u108"},
    "366507f87ae9464094c573b046e4ad2e":{
      "scriptId":"u109"},
    "8072d36c39564d929de33f3a95ca39cb":{
      "scriptId":"u110"},
    "7858a949e5344f658059b3ed29027612":{
      "scriptId":"u111"},
    "4593a81c89e348d2af57d7427b709dee":{
      "scriptId":"u112"},
    "aaa485dd561b4ba183403e096e6a046e":{
      "scriptId":"u113"},
    "0050621a81c8419e91d0de36597ac8f2":{
      "scriptId":"u114"},
    "2d7ec2cf03d74f489c3a5f7a74af648a":{
      "scriptId":"u115"},
    "e4e42bd0011748b69452c9fa81051b2b":{
      "scriptId":"u116"},
    "017b1a95f7e94d26ae80a65421e1826a":{
      "scriptId":"u117"},
    "5c900d41816a45cdbb812e73818435b7":{
      "scriptId":"u118"},
    "a3435463d09d4be6a341747a89c3358d":{
      "scriptId":"u119"}}});