$axure.loadCurrentPage({
  "url":"各种弹窗.html",
  "generationDate":new Date(1474526382538.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"44e9473661974f45a6a607e6cda612ab",
    "type":"Axure:Page",
    "name":"各种弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ca31eb19accc42daaf0e28549cb4c1a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":1530},
            "size":{
              "width":270,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5c101240ed3442298e5e3e13f41c693",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":795,
                  "y":1530},
                "size":{
                  "width":270,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u0.png"}},
{
          "id":"01d5c70a1d5e4566b385f517863d81a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1210},
            "size":{
              "width":380,
              "height":330}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21e84f10abaa45d5b3790fa3957d9b24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1210},
                "size":{
                  "width":380,
                  "height":330}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u2.png"}},
{
          "id":"1f01856a1b134d9aaaccebaff8a624e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1224},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f6b9fd37df43269fdf448b9b63003c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":1224},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5ff9c1b7a6443a198c2d71126e1a692",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1250},
            "size":{
              "width":380,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u6_line.png"}},
{
          "id":"a3deb4c397b0445fbe1a4fdb8350459f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":118,
              "y":1333},
            "size":{
              "width":113,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"68c5997967404d8aa446509b117a289f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1301},
            "size":{
              "width":96,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2620c6c4a0c0495d8d03f25f918d2281",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1301},
                "size":{
                  "width":96,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9f65326d5334dacbc36b47facc1bea2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1337},
            "size":{
              "width":70,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67569aa3e5df43d794d349b083f1dba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1337},
                "size":{
                  "width":70,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64d71024155046fdbad83fc7757f666f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":1301},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e402e3fd4fc47fa954279839cca98e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":1301},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d41cb945c51e4325884cb03a59e9b569",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":1374},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79d8889cf2fd41cb920e6762c5b059d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":1374},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04d63881a05d4b9f92d2d5af3cb291b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":160,
              "y":1430},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61721977990546f8ac9d7ed350a56b00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":160,
                  "y":1430},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u16.png"}},
{
          "id":"48387f54ca214a1e9f9f43cf8b960191",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":282,
              "y":1437},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30e40ea8ce154a62a63761d8491d9fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":1437},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2552eb9105b4410a83d977573b708fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":20,
              "y":1510},
            "size":{
              "width":160,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36767e0e589a47eca56b2b6a00043a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":1510},
                "size":{
                  "width":160,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"235a65ab44fa477a935739b9932529f4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1490},
            "size":{
              "width":380,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u6_line.png"}},
{
          "id":"a6651bed606d494d931c6d13e082b641",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":352,
              "y":1223},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d74b0d6fde47b199cee23124f2e75a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":352,
                  "y":1223},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c2e266b968d4f49bc07052ff013365d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":1374},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165eba43238d48628ddbb8d3ccc86d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":1374},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"850442cfdb154854b9a9f2f76378e3ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":1510},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f93594ea80f46c587a22250b2e17479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":1510},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04298ca86a4b4d7b9b0a48dbeb21168d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1270},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1096fd615ec14ce281de30119b17bb16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1270},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a7e4df3a7f047048095a69de990cb07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":40,
              "y":1270},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a28d325c1c4050bdc571ab1430644f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":1270},
                "size":{
                  "width":340,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84b5390453d44d7995ccf7f871b5b657",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1257},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be068a23efc04a898ae4203cec3a1ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1257},
                "size":{
                  "width":130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u33.png"}},
{
          "id":"c4ce5343a14f44c9b6eb750d81fdc23f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":790,
              "y":1275},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade10956df3249e1abecd3b5d71051ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":790,
                  "y":1275},
                "size":{
                  "width":340,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cee1d848a824bd485278da426da7591",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1430},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880dda78d7ae49159a076849165a33d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1430},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u37.png"}},
{
          "id":"f2a0d4b4236d44ecae1fb5dc306c7c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":790,
              "y":1450},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1173a10ab8944e28a42a4406865ee04c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":790,
                  "y":1450},
                "size":{
                  "width":340,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"226051ffabe04673bf8d9686defc7f48",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1560},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a3f0c0dfc7940b19fad3d5c02a33c7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1560},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u37.png"}},
{
          "id":"d80edadc2b354b0382bde42d5efca19c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":820,
              "y":1577},
            "size":{
              "width":240,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"931d66b97e814e5691aaceed33a14265",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":820,
                  "y":1577},
                "size":{
                  "width":240,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c5eb0f8da3949b68046b5be75844854",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1590},
            "size":{
              "width":380,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c2300384a9f4c8489eb568d86d4865d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":1590},
                "size":{
                  "width":380,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u45.png"}},
{
          "id":"99a0f2bdcd864c59a40a26237a7771c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":31,
              "y":1652},
            "size":{
              "width":338,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcc69e949cfd4a6ea9b756dd2ec814c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":31,
                  "y":1652},
                "size":{
                  "width":338,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a19f9a24aecf4800b9057b7fe9c71003",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":357,
              "y":1608},
            "size":{
              "width":12,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfaa557cb3a345b3a45547a848bdcf44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":357,
                  "y":1608},
                "size":{
                  "width":12,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c615417db0c049788d14d3a73ec8a6fd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":1340},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26f8e4e2f7c64274a0a6dc11a04fcb14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":1340},
                "size":{
                  "width":130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u33.png"}},
{
          "id":"29e801bd8b9e4cdab986e618fc9bb24b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":790,
              "y":1358},
            "size":{
              "width":340,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"344b1c601cb84654a6c44bdfe7e63f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":790,
                  "y":1358},
                "size":{
                  "width":340,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"734d92e786314abaa1dcea0e8ad31b5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":408},
            "size":{
              "width":350,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9da5c9e9dd41408fb672711ec4172ffe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":408},
                "size":{
                  "width":350,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u55.png"}},
{
          "id":"a18ecee25bb0455bbd20bbca693a86a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"24px",
            "location":{
              "x":80,
              "y":461},
            "size":{
              "width":200,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e144d3550ab4410fb13ed776f5fb9452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"24px",
                "location":{
                  "x":80,
                  "y":461},
                "size":{
                  "width":200,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dacf352393b488993862885a38ae329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":80,
              "y":429},
            "size":{
              "width":154,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10416d7e67e641298fbccfa0040a23f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":80,
                  "y":429},
                "size":{
                  "width":154,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6aa1a8890c47a2ba5c74f931c1b8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":99,
              "y":521},
            "size":{
              "width":112,
              "height":33},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d7427f7669142a2a04ea6c0fadd290f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":99,
                  "y":521},
                "size":{
                  "width":112,
                  "height":33},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/各种弹窗/u61.png"}},
{
          "id":"ed35c5ab0ade4c80809fb31c2514efab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":330,
              "y":412},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78657e53e9894cc1b0fe22f4bbc2e9c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":330,
                  "y":412},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea25e552bfe241f094cf03fc347bfa13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":655},
            "size":{
              "width":350,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b234f202d5345f0b2b200feb1fee9ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":655},
                "size":{
                  "width":350,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u55.png"}},
{
          "id":"f323256901714efc9edcc3114901ce14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":703},
            "size":{
              "width":190,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d172116f94ef4345ac47faa7fa0ad25b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":703},
                "size":{
                  "width":190,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c53b5338055430f86ed438d49a98974",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":114,
              "y":766},
            "size":{
              "width":112,
              "height":33},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0261e4f983f4168a05a69433ccf4899",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":114,
                  "y":766},
                "size":{
                  "width":112,
                  "height":33},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 http://vip.csdn.net/home/index",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://vip.csdn.net/home/index",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/各种弹窗/u61.png"}},
{
          "id":"32b2219fbad34ce1813d335300b23f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":330,
              "y":659},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7430b5ce47d488189e4a3974c533e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":330,
                  "y":659},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df81fbfe3487465a894f7b08f0f7f69f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":903},
            "size":{
              "width":410,
              "height":207},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d96d9b00c354516ab17ad3ee63b831b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":903},
                "size":{
                  "width":410,
                  "height":207},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u73.png"}},
{
          "id":"31fa034f1ace45e7959f88e334892b20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":85,
              "y":977},
            "size":{
              "width":205,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a46e30b58d466793545b52e89ac901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":85,
                  "y":977},
                "size":{
                  "width":205,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca29a2581f3f4018acf1773448c59cf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":124,
              "y":1024},
            "size":{
              "width":112,
              "height":33},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ccf3bf8377749d8aa7d6dc3ffff2985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":124,
                  "y":1024},
                "size":{
                  "width":112,
                  "height":33},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"点击后直接下载"},
          "images":{
            "normal~":"images/各种弹窗/u61.png"}},
{
          "id":"e23b89b4786243bbb5aa92733b77e9b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":389,
              "y":917},
            "size":{
              "width":17,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6893568dab2f43dd8136440682a15806",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":389,
                  "y":917},
                "size":{
                  "width":17,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e373dfb9d974e63baeb230ae89dc7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":1069},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44aed77f068d40d8a7d70ffccdb6e487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":1069},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d414f6b2e453481eb07ba3b0786f6da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "lineSpacing":"28px",
            "location":{
              "x":40,
              "y":933},
            "size":{
              "width":330,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa1f7fec8d3347f39abc038be78fdf24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "lineSpacing":"28px",
                "location":{
                  "x":40,
                  "y":933},
                "size":{
                  "width":330,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df6b7c93c99b4f08ad8f8fbb485c7d95",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":46},
            "size":{
              "width":400,
              "height":285}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0e8ec7d20ad466a9dac2cbf873e83f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":46},
                "size":{
                  "width":400,
                  "height":285}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/各种弹窗/u85.png"}},
{
          "id":"f7c0906af6d2477e862ffd695d369d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":378},
            "size":{
              "width":460,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bc11640da1d40d0be8ac2785b2a3308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":378},
                "size":{
                  "width":460,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e9ffe15a93a47a9ad74955c6dcc3410",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":20,
              "y":618},
            "size":{
              "width":410,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8a93270348948a4848bb71ab95193dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":20,
                  "y":618},
                "size":{
                  "width":410,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9baf778ca3f4772ad8e8c4cbd560345",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":10,
              "y":863},
            "size":{
              "width":410,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54b4ce2c5f3f4e72a789d1707cf8ef8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":10,
                  "y":863},
                "size":{
                  "width":410,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c03deaf028467483ea21dafa0c888e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":29,
              "y":14},
            "size":{
              "width":391,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85541264f67f4b4abdfa1ba1a7d45e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":29,
                  "y":14},
                "size":{
                  "width":391,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebada5e49f70437ab83d5600f3338f60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":1069},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d29fbf080ed4a2789f443913086181e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":1069},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5916de4aa7da41dca7e0af3f380ec909",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":20,
              "y":1168},
            "size":{
              "width":410,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98bbca3e81a4460b82396051bcbf8a2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":20,
                  "y":1168},
                "size":{
                  "width":410,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f86097f7fb4f49c1b7a87446fea7bfb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":668},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"745175d758e3451a8bdc8a8ad2b303b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":668},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9278ef9f2844796aaa0129c3a55362c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":209,
              "y":1069},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14d672a382ba4eecb13f61393e54d0e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":1069},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f4438e0ff0e44404beab6e9d92a5597b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":341},
            "size":{
              "width":1038,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u103_line.png"}},
{
          "id":"25e83c14fa624c3289f88937e241d57a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":598},
            "size":{
              "width":978,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u104_line.png"}},
{
          "id":"1c2f2e01fcc049889821d44c56c041be",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":843},
            "size":{
              "width":929,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u105_line.png"}},
{
          "id":"d4026b81b4114d8ca19230efae497605",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1140},
            "size":{
              "width":1000,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/各种弹窗/u106_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ca31eb19accc42daaf0e28549cb4c1a5":{
      "scriptId":"u0"},
    "d5c101240ed3442298e5e3e13f41c693":{
      "scriptId":"u1"},
    "01d5c70a1d5e4566b385f517863d81a7":{
      "scriptId":"u2"},
    "21e84f10abaa45d5b3790fa3957d9b24":{
      "scriptId":"u3"},
    "1f01856a1b134d9aaaccebaff8a624e3":{
      "scriptId":"u4"},
    "a2f6b9fd37df43269fdf448b9b63003c":{
      "scriptId":"u5"},
    "f5ff9c1b7a6443a198c2d71126e1a692":{
      "scriptId":"u6"},
    "a3deb4c397b0445fbe1a4fdb8350459f":{
      "scriptId":"u7"},
    "68c5997967404d8aa446509b117a289f":{
      "scriptId":"u8"},
    "2620c6c4a0c0495d8d03f25f918d2281":{
      "scriptId":"u9"},
    "c9f65326d5334dacbc36b47facc1bea2":{
      "scriptId":"u10"},
    "67569aa3e5df43d794d349b083f1dba6":{
      "scriptId":"u11"},
    "64d71024155046fdbad83fc7757f666f":{
      "scriptId":"u12"},
    "3e402e3fd4fc47fa954279839cca98e7":{
      "scriptId":"u13"},
    "d41cb945c51e4325884cb03a59e9b569":{
      "scriptId":"u14"},
    "79d8889cf2fd41cb920e6762c5b059d7":{
      "scriptId":"u15"},
    "04d63881a05d4b9f92d2d5af3cb291b2":{
      "scriptId":"u16"},
    "61721977990546f8ac9d7ed350a56b00":{
      "scriptId":"u17"},
    "48387f54ca214a1e9f9f43cf8b960191":{
      "scriptId":"u18"},
    "30e40ea8ce154a62a63761d8491d9fa4":{
      "scriptId":"u19"},
    "f2552eb9105b4410a83d977573b708fe":{
      "scriptId":"u20"},
    "36767e0e589a47eca56b2b6a00043a03":{
      "scriptId":"u21"},
    "235a65ab44fa477a935739b9932529f4":{
      "scriptId":"u22"},
    "a6651bed606d494d931c6d13e082b641":{
      "scriptId":"u23"},
    "25d74b0d6fde47b199cee23124f2e75a":{
      "scriptId":"u24"},
    "7c2e266b968d4f49bc07052ff013365d":{
      "scriptId":"u25"},
    "165eba43238d48628ddbb8d3ccc86d07":{
      "scriptId":"u26"},
    "850442cfdb154854b9a9f2f76378e3ac":{
      "scriptId":"u27"},
    "4f93594ea80f46c587a22250b2e17479":{
      "scriptId":"u28"},
    "04298ca86a4b4d7b9b0a48dbeb21168d":{
      "scriptId":"u29"},
    "1096fd615ec14ce281de30119b17bb16":{
      "scriptId":"u30"},
    "4a7e4df3a7f047048095a69de990cb07":{
      "scriptId":"u31"},
    "b5a28d325c1c4050bdc571ab1430644f":{
      "scriptId":"u32"},
    "84b5390453d44d7995ccf7f871b5b657":{
      "scriptId":"u33"},
    "be068a23efc04a898ae4203cec3a1ba2":{
      "scriptId":"u34"},
    "c4ce5343a14f44c9b6eb750d81fdc23f":{
      "scriptId":"u35"},
    "ade10956df3249e1abecd3b5d71051ab":{
      "scriptId":"u36"},
    "3cee1d848a824bd485278da426da7591":{
      "scriptId":"u37"},
    "880dda78d7ae49159a076849165a33d5":{
      "scriptId":"u38"},
    "f2a0d4b4236d44ecae1fb5dc306c7c29":{
      "scriptId":"u39"},
    "1173a10ab8944e28a42a4406865ee04c":{
      "scriptId":"u40"},
    "226051ffabe04673bf8d9686defc7f48":{
      "scriptId":"u41"},
    "7a3f0c0dfc7940b19fad3d5c02a33c7d":{
      "scriptId":"u42"},
    "d80edadc2b354b0382bde42d5efca19c":{
      "scriptId":"u43"},
    "931d66b97e814e5691aaceed33a14265":{
      "scriptId":"u44"},
    "9c5eb0f8da3949b68046b5be75844854":{
      "scriptId":"u45"},
    "7c2300384a9f4c8489eb568d86d4865d":{
      "scriptId":"u46"},
    "99a0f2bdcd864c59a40a26237a7771c1":{
      "scriptId":"u47"},
    "dcc69e949cfd4a6ea9b756dd2ec814c9":{
      "scriptId":"u48"},
    "a19f9a24aecf4800b9057b7fe9c71003":{
      "scriptId":"u49"},
    "dfaa557cb3a345b3a45547a848bdcf44":{
      "scriptId":"u50"},
    "c615417db0c049788d14d3a73ec8a6fd":{
      "scriptId":"u51"},
    "26f8e4e2f7c64274a0a6dc11a04fcb14":{
      "scriptId":"u52"},
    "29e801bd8b9e4cdab986e618fc9bb24b":{
      "scriptId":"u53"},
    "344b1c601cb84654a6c44bdfe7e63f38":{
      "scriptId":"u54"},
    "734d92e786314abaa1dcea0e8ad31b5c":{
      "scriptId":"u55"},
    "9da5c9e9dd41408fb672711ec4172ffe":{
      "scriptId":"u56"},
    "a18ecee25bb0455bbd20bbca693a86a6":{
      "scriptId":"u57"},
    "e144d3550ab4410fb13ed776f5fb9452":{
      "scriptId":"u58"},
    "4dacf352393b488993862885a38ae329":{
      "scriptId":"u59"},
    "10416d7e67e641298fbccfa0040a23f5":{
      "scriptId":"u60"},
    "9a6aa1a8890c47a2ba5c74f931c1b8cc":{
      "scriptId":"u61"},
    "0d7427f7669142a2a04ea6c0fadd290f":{
      "scriptId":"u62"},
    "ed35c5ab0ade4c80809fb31c2514efab":{
      "scriptId":"u63"},
    "78657e53e9894cc1b0fe22f4bbc2e9c2":{
      "scriptId":"u64"},
    "ea25e552bfe241f094cf03fc347bfa13":{
      "scriptId":"u65"},
    "1b234f202d5345f0b2b200feb1fee9ac":{
      "scriptId":"u66"},
    "f323256901714efc9edcc3114901ce14":{
      "scriptId":"u67"},
    "d172116f94ef4345ac47faa7fa0ad25b":{
      "scriptId":"u68"},
    "9c53b5338055430f86ed438d49a98974":{
      "scriptId":"u69"},
    "e0261e4f983f4168a05a69433ccf4899":{
      "scriptId":"u70"},
    "32b2219fbad34ce1813d335300b23f39":{
      "scriptId":"u71"},
    "f7430b5ce47d488189e4a3974c533e0e":{
      "scriptId":"u72"},
    "df81fbfe3487465a894f7b08f0f7f69f":{
      "scriptId":"u73"},
    "2d96d9b00c354516ab17ad3ee63b831b":{
      "scriptId":"u74"},
    "31fa034f1ace45e7959f88e334892b20":{
      "scriptId":"u75"},
    "e2a46e30b58d466793545b52e89ac901":{
      "scriptId":"u76"},
    "ca29a2581f3f4018acf1773448c59cf6":{
      "scriptId":"u77"},
    "4ccf3bf8377749d8aa7d6dc3ffff2985":{
      "scriptId":"u78"},
    "e23b89b4786243bbb5aa92733b77e9b4":{
      "scriptId":"u79"},
    "6893568dab2f43dd8136440682a15806":{
      "scriptId":"u80"},
    "4e373dfb9d974e63baeb230ae89dc7df":{
      "scriptId":"u81"},
    "44aed77f068d40d8a7d70ffccdb6e487":{
      "scriptId":"u82"},
    "d414f6b2e453481eb07ba3b0786f6da9":{
      "scriptId":"u83"},
    "fa1f7fec8d3347f39abc038be78fdf24":{
      "scriptId":"u84"},
    "df6b7c93c99b4f08ad8f8fbb485c7d95":{
      "scriptId":"u85"},
    "a0e8ec7d20ad466a9dac2cbf873e83f9":{
      "scriptId":"u86"},
    "f7c0906af6d2477e862ffd695d369d9a":{
      "scriptId":"u87"},
    "0bc11640da1d40d0be8ac2785b2a3308":{
      "scriptId":"u88"},
    "3e9ffe15a93a47a9ad74955c6dcc3410":{
      "scriptId":"u89"},
    "e8a93270348948a4848bb71ab95193dc":{
      "scriptId":"u90"},
    "b9baf778ca3f4772ad8e8c4cbd560345":{
      "scriptId":"u91"},
    "54b4ce2c5f3f4e72a789d1707cf8ef8b":{
      "scriptId":"u92"},
    "d8c03deaf028467483ea21dafa0c888e":{
      "scriptId":"u93"},
    "85541264f67f4b4abdfa1ba1a7d45e1a":{
      "scriptId":"u94"},
    "ebada5e49f70437ab83d5600f3338f60":{
      "scriptId":"u95"},
    "0d29fbf080ed4a2789f443913086181e":{
      "scriptId":"u96"},
    "5916de4aa7da41dca7e0af3f380ec909":{
      "scriptId":"u97"},
    "98bbca3e81a4460b82396051bcbf8a2b":{
      "scriptId":"u98"},
    "f86097f7fb4f49c1b7a87446fea7bfb0":{
      "scriptId":"u99"},
    "745175d758e3451a8bdc8a8ad2b303b6":{
      "scriptId":"u100"},
    "d9278ef9f2844796aaa0129c3a55362c":{
      "scriptId":"u101"},
    "14d672a382ba4eecb13f61393e54d0e9":{
      "scriptId":"u102"},
    "f4438e0ff0e44404beab6e9d92a5597b":{
      "scriptId":"u103"},
    "25e83c14fa624c3289f88937e241d57a":{
      "scriptId":"u104"},
    "1c2f2e01fcc049889821d44c56c041be":{
      "scriptId":"u105"},
    "d4026b81b4114d8ca19230efae497605":{
      "scriptId":"u106"}}});